export type RootStackParamList = {
  Home: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  EditProfile: undefined;
  ProductDetail: { productId: string };
  ProductListByCategory: { category: string };
  Search: undefined;
  Favorite: undefined;
  Category: undefined;
  Login: undefined;
  Cart: undefined;
  Payment: undefined;
  MockPayment: { linkedMethod?: string } | undefined;
  LinkAccount: { methodId: string; methodName: string };
  Receipt: { methodId: string; methodName: string; amount: number };
  OrderPending: { methodId: string; methodName: string };
  Profile: undefined;
  MyOrders: undefined;
  SuccessPayment: undefined;
};
